### ISSUE TITLE
Can't disable custom crafts

### ISSUE THREAD

**Issue by survetman** [mmopluginteam/mmoitems#104]
Hello !
We have this configuration:

Server info:

- git-Paper-229
- MMOItems 5.4.1
- MMOLib 1.1.2

I detect that this problem comes back. Vanilla crafts are replaced by Customs craft even if we have this: disable-craftings: true
 Edit: this is the same thing than here https://github.com/Indyuce/mmoitems/issues/77 but with the newest configuration

**Comment by Joshinn-mc** [comment]
@survetman I believe you're missing something...

You put "We have this configuration:" but didn't actually include the configuration for us to test.

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
