### ISSUE TITLE
Sound not playing on Attack or other interactions 

### ISSUE THREAD

**Issue by SkyDevil-** [mmopluginteam/mmoitems#107]
When applying a sound to play on a custom weapon or item. During attack interaction etc

Create a new weapon and select play sound on attack or interact

**Expected behavior**
To play sound when attacking or interactions, obtaining or crafting 

**Server info:**
 - Spigot Build & Version
   MC 1.15.2 R0.1 
 - MMOItems 5.4.2

**Additional context**
https://pastebin.com/ysYq4Bgz

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
