### ISSUE TITLE
Question / Bug report

### ISSUE THREAD

**Issue by Shadoves** [mmopluginteam/mmoitems#109]
Hello together!

First of all : Very nice and useful plugin!

I am reporting a holo bug: The Holographic Display dont remove themself : see in pic

http://prntscr.com/smtvhn

Many thanks!

Best greetings

Shadow

**Comment by Shadoves** [comment]
For Information: I use the lastest version of CMI

**Comment by Joshinn-mc** [comment]
@Shadoves This is a known issue with CMI as a hologram API, and is simply not something we can control. Alot of our users have better luck when they also install "Holograms" or "Holographic Displays" to hook into for the holograms API.

**Comment by sguo1123** [comment]
Even with the latest versions of CMI, Holograms, and MMOItems, some holo dmg indicators still stick, and it seems to differ based on each client. (i.e. Some of my holos get stuck but different ones for my friend, in the same area.)

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
