### ISSUE TITLE
Potion Effect Regeneration 1 on armour sets don't work

### ISSUE THREAD

**Issue by NRobbo** [mmopluginteam/mmoitems#110]
Pretty simply explained by the title. 

I have added potion effect of regeneration to a full set of armour and it doesn't work. I know this is probably a bug since the the actual effect is active (on the inventory screen) but no health is regenerated. My theory is the potion effect is being refreshed too quickly for the health regeneration tick to activate.

If i use regeneration level 2 it works perfectly fine no problem which tells me im doing everything right in the config files.

**Comment by Flirtey** [comment]
@NRobbo Would you go ahead and please provide logs and the example config just to duplicate exactly.

**Comment by NRobbo** [comment]
More Info:
Spigot ver: Paper 284
Mi Ver: 5.4 (i know it isnt the newest but ive not had an issue with this version at all)
Armor.YML https://pastebin.com/G8yHXPAT
item-sets.yml https://pastebin.com/NmxKD7wH
Latest startup server log: https://pastebin.com/UJF8MNbC

Equipping full Golden Armor grabbed from Mi (not just vanilla gold). I actually do get regeneration 1 when i open the inventory screen so i know everything works however it doesnt actually regen health. 

As you can see in the item-sets.yml i have made other item sets that work perfectly also.

Let me know if you need more info.

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
