### ISSUE TITLE
i need disable Drop your plugin

### ISSUE THREAD

**Issue by Meawku** [mmopluginteam/mmoitems#113]
**Describe the bug**
 i use plugin LevelledMobs then they not get more drop
that why i want to disable
 tell my step by step ok

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
