### ISSUE TITLE
Attack Damage

### ISSUE THREAD

**Issue by Joshinn-mc** [mmopluginteam/mmoitems#115]
**Describe the bug**
On the latest version of MMOLib, 1.1.12 or whatever, and latest MMOItems dev of 5.4.2, theres a small but noticeable stat bug.

On a fresh server, all players attack damage is 1 as it should be, and its always fine until you equip an mmoitems weapon that effects attack damage. After you have touched something that efffects attack damage, you are permanently now dealing 2 damage with your fist instead of 1. It's a permanent +1 attack buff after mmoitems touches your stats.

**To Reproduce**
1. New fresh userdata (important)

2. Hit some stuff, check your base attack damage to be 1 in exploreattributes.

3. Equip an mmoitems sword that modifies attack damage, throw it away.

4. Check your new base damage in exploreattributes.

**Expected behavior**
Shouldnt permanently effect attack damage.

**Screenshots**
Not applicable

**Server info:**
 - Latest PAper 342 I believe
 - 5.4.2
 - No other plugins involved.

**Additional context**

**Comment by Indyuce** [comment]
Fixed in the latest MMOLib GitHub release as long as you toggle on the _fix-player-attributes_ config option
