### ISSUE TITLE
Want to add custom damage type for RPG

### ISSUE THREAD

**Issue by yangjohn123** [mmopluginteam/mmoitems#118]
I have made a nice world of RPG and want to create many classes and items, but when I want to create new element damage. I can not find anyway to do it, this is make my idea of my RPG become limit by the settings.

So I want to ask for to make a way let people to create there own damage type and damage formula.

**Comment by Indyuce** [comment]
Closing that ticket and adding this idea to #132

**Comment by Indyuce** [comment]
We nee
