### ISSUE TITLE
[Suggestion] Be able to make blank lines between categories in the lore of items

### ISSUE THREAD

**Issue by Azuuno** [mmopluginteam/mmoitems#123]
Hi, I suggest to add a way to add blank lines between categories in the lore of items. It can be useful to get more visiblity of the stats ^^. (Sorry if I'm not explaining clearly, I'm not english)

What I mean by "categories" are the ones which we can customize in lore-format.yml (you can see the screenshot under this message, the categories are surrounded by red rectangles) : 
![image](https://user-images.githubusercontent.com/57075860/85607820-c3ff0680-b654-11ea-8212-311ce876757f.png)

**Comment by Ehhthan** [comment]
{bar} and {sbar} provides this already.
