### ISSUE TITLE
[BUG] Undead Damage reduction not working on items

### ISSUE THREAD

**Issue by Dynamite99** [mmopluginteam/mmoitems#126]
https://pastebin.com/J3c9k98C

getting this error on the alatest version of mmoitems. It seems that undead-damage-reduction is not recognized in armor sets. This is similar to the mmocore issue I am having in the other ticket where pve-damage-reduction is not recognized in classes as a possible stat. If you check the stats.yml, pvp, pve, and undead damage reduction are all missing

**Comment by Ghmmy** [comment]
there isnt a undead-damage-reduction modifier fyi. Only undead-damage.

**Comment by Dynamite99** [comment]
> there isnt an undead-damage-reduction modifier fyi. Only undead-damage.

Are you sure? it appears in the item GUI maker menu

**Comment by Indyuce** [comment]
There's no undead damage reduction stat
