### ISSUE TITLE
Dying with Soulbound item in region with keep-inventory flag from WG Extra Flags duplicates the item.

### ISSUE THREAD

**Issue by AshenGaming** [mmopluginteam/mmoitems#134]
*Raised by **@Kub** on the Discord.*

**Describe the bug**
So I'm using this plugin: https://www.spigotmc.org/resources/worldguard-extra-flags.4823/
and there's a flag called keep-inventory. When dying with a soulbound item in a region with this flag, the item is duplicated.

**To Reproduce**
1. Create a WorldGuard region and add the `keep-inventory` flag to it.
2. Have a soulbound MMOItem in your inventory
3. Die
4. Item gets duplicated

**Expected behavior**
The item should not be duplicated and should instead just stay in the inventory.

**Server info:**
 - Paper 1.15.2
 - Plugin Version
 - WorldGuard Extra Flags

**Comment by Indyuce** [comment]
This should be fixed in the latest dev build
