### ISSUE TITLE
CLASS CONDITION for CRAFTING

### ISSUE THREAD

**Issue by kiloRs** [mmopluginteam/mmoitems#140]
**Describe the bug**
The Class{list=####,####} doesn't work. Throws errors.
However, only having 1 class listed works.

**To Reproduce**
Make a condition for a custom crafting table recipe using 2 classes at once.
**Expected behavior**
Error?

**Screenshots**
![image](https://user-images.githubusercontent.com/48230591/87104097-7e2d6b00-c21c-11ea-8966-3a0c6fe050a6.png)

**Server info:**
 - 1.16.1
 - 5.5.1 Latest Dev (Unsure of number, as of todays date)

**Additional context**

**Comment by Indyuce** [comment]
Have you tried adding " around the classes names list? e.g `class{list="ROGUE,MARKSMAN"}`

**Comment by Joshinn-mc** [comment]
@kiloRs 
^
