### ISSUE TITLE
Stats in Item-Sets not working

### ISSUE THREAD

**Issue by kiloRs** [mmopluginteam/mmoitems#141]
**Describe the bug**
max-stamina
stamina-regeneration:
mana-regeneration
^dont work

**To Reproduce**
use these stats in a item set

**Expected behavior**
error produced on startup saying the stat is wrong no matter how it is written (max-stamina, max_stamina)

**Screenshots**

**Server info:**
 1.16.1
5.5.1

**Additional context**

**Comment by Indyuce** [comment]
Will be fixed in the next dev build
