### ISSUE TITLE
API Additions

### ISSUE THREAD

**Issue by Ehhthan** [mmopluginteam/mmoitems#143]
- Add an event for when an item is generated or built.

- Whenever an item is generated through the gui, reload the random stats.

**Comment by Indyuce** [comment]
I've added an option to item edition GUIs to reroll the item stats, that should make editing items easier. However I'm not sure how that event would be used, have you thought about registering a stat in order to modify the item ?

**Comment by Ehhthan** [comment]
I'm writing a plugin that tracks specific mmoitems. It works by applying a uuid to the nbt of the item and whenever an item is generated I want to make the database information.

**Comment by Indyuce** [comment]
Can't you register an ItemStat to apply the UUID to the item?
