### ISSUE TITLE
resistances don't work with negative values anymore

### ISSUE THREAD

**Issue by emanuelitor** [mmopluginteam/mmoitems#144]
**Describe the bug**
setting fall damage reduction (or magic damage reduction, physical damage reduction and other types) to a negative value doesn't work properly.
**To Reproduce**
1. create a new armor boots item, give it something like -50% fall damage reduction and try jumping somewhere to take fall damage.
2. in mmoitems ver 5.3.2 (and paper 1.15.2) you wil get more fall damage with those boots equipped and in the latest version you will take the same damage without the boots as with the boots equipped.
3. 99% sure that it applies to other damage types but can't test atm.

**Expected behavior**
negative values should work.

**Server info:**
 - paper-87 (1.16.1)
 - mmoitems 5.5.1

**Additional context**
this doesn't affect things like movement speed or max-health.

**Comment by Indyuce** [comment]
This issue will be fixed in the next MMOLib release
