### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent [1.16.1]

### ISSUE THREAD

**Issue by DogeTennant** [mmopluginteam/mmoitems#145]
Hello this error shows up in the console everytime any player hits any mob.

https://pastebin.com/yqZ4ncHR

Our MMOLib version is 1.2.4 and MMOItems is 5.5.1

edit: Also we run Spigot, not Paper

**Comment by MuTBu** [comment]
bro I have the same thing :(

**Comment by MuTBu** [comment]
i running Paper

**Comment by Indyuce** [comment]
Give MMOItems 5.5.3 a try and see if the issue persists

**Comment by DogeTennant** [comment]
Tried the newest MMOItems version and everything works fine,

thanks!
