### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by Dreyd** [mmopluginteam/mmoitems#146]
Hello, is somehow possible to create any consumable or gem(or any other options) which add more gemslots?
Example: I create gem with name Gemslots upgrader and when i drag this gem to item I want to add new gemstone slot to the item.

Next question : Can I make visible item durability in item bar or somewhere? My players keep breaking their armors and items when they are bossfighting because they see durability of item only when they drag mouse on item(durability in stats) but when they are fighting this way to look for durability is bad.. So if there is some way how to make for players visible durability bar somewhere else then in stats of item, say me where please or help me. thanks anyone and have good day

**Comment by Dreyd** [comment]
I see MMOitems provide durability bar in default mc vanilla bar, but not for me... I know why now.
The reason why i dont see durability bar at itembar is enchants... when i remove enchants from item, its shows both durabilities(vanilla mc and on item when u drag mouse on it) but when enchants are on item, vanilla mc durability bar dont work...

**Comment by Joshinn-mc** [comment]
@Dreyd MMOItems 5.2 is extremely outdated and we can't provide any help with that.

Please update and you will notice that the durability bar issue is fixed.

**Comment by Dreyd** [comment]
On my server we got so many items created and used by players and so many items in game. and when we update to any other newer version than 5.2 all items are broken, they are in game still, looking same with same lore and name but they are not same,, they dont stack together and they cant be used in quests,trades with villagers and all..

**Comment by Joshinn-mc** [comment]
You're using an extremely old version, some things have changed. We can't do anything to help you if you won't update. That is technological debt and your problem will only continue to get worse as yo uwait.

If you need help please join our support discord so we can help you with updating.
