### ISSUE TITLE
[MMOItems 5.5.3] Spam log

### ISSUE THREAD

**Issue by Florianpal1** [mmopluginteam/mmoitems#147]
**Describe the bug**
The plugin generates an important spam of log

**To Reproduce**
1. Have a mmoitems
2. Use this items

**Expected behavior**
The suppression of this log

**Screenshots**

![image](https://user-images.githubusercontent.com/36370356/87450427-c96dc200-c5fe-11ea-80ac-e1aecaeae943.png)

**Server info:**
 - Paper-90 1.16.1
 - MMOitems 5.5.3

**Comment by Joshinn-mc** [comment]
Please provide the items in question and a full log of the server. I can't replicate this with what you provided.
