### ISSUE TITLE
Player Heads Lose Data Upon Dropping

### ISSUE THREAD

**Issue by Dancull47** [mmopluginteam/mmoitems#148]
**Describe the bug**
When a Player-Head is dropped on the group, it looses its Data
**To Reproduce**
1.Get Player Head item
2.Drop
3.Pickup
**Expected behavior**
Not lose data
**Screenshots**
https://i.imgur.com/eL75eSo.gif
**Server info:**
 - Paper 374
 - MMOItems-5.5.3-SNAPSHOT.jar

**Comment by Indyuce** [comment]
It's most likely not due to MMOItems.. I see you have other plugins reacting when items are dropped on the ground. You will need to run MMOItems on a separate server and remove your plugins one by one to isolate any involved plugin

**Comment by Ehhthan** [comment]
Closed due to no response.
