### ISSUE TITLE
knockback resistance in 1.16

### ISSUE THREAD

**Issue by emanuelitor** [mmopluginteam/mmoitems#150]
**Describe the bug**
In 1.15 this stat gave you a % chance to completely ignore knockback (not 100% sure about that but lets go with it)
In 1.16 mojang made it so knockback resistance stat reduces knockback
And now what happens is whenever something has knockback resistance it will take recuded knockback AND also have a chance to ignore knockback.
It doesn't matter if its just regular netherite armor or an mmoitem with the knockback resistance stat... the result will be the same

**To Reproduce**
start 2 mc clients, get them on the server, give one of them just regular netherite armor set and start punching him on your 2nd client and he should ignore knockback about 40% of the time

**Expected behavior**
the player shouldn't ignore knockback

**Server info:**
mmoitems 5.5.3
paper-90

**Additional context**
just change it so the plugin doesn't use the same value for knockback ignoring as the vanilla knockback resist stat
but imo the knockback ignoring is unnecessary now that knockback resistance is a thing
(edit)
on the second note this might be a problem in mmocore since i have both

**Comment by Indyuce** [comment]
The MMOItems KR stat is entirely based on the corresponding vanilla player attribute (generic.knockback_resistance), it's not something we can really change. Any change made to the attribute will affect the MI stat
