### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by DarkPaJl** [mmopluginteam/mmoitems#153]
Hello, I have a problem related to the statistics of armor, the problem is that on my server about 100 levels, and armor with swords naturally also goes up to 100 LVL, but the problem is that the maximum protection that I can set is 20, although at 100 level I have damage in swords and bows is 800-1200, it follows that the armor is already at 10 level stops growing and becomes the same that at 10 level that at 100 level, you could change the limit of armor from 20 to 10000?

**Comment by Ehhthan** [comment]
Armor is a vanilla limitation so changing the max would be impossible.

**Comment by Joshinn-mc** [comment]
Minecraft caps this as 20, we can not change it. Please use the other stats we provide.
