### ISSUE TITLE
Error when Using Custom Sounds on Consumable

### ISSUE THREAD

**Issue by Dynamite99** [mmopluginteam/mmoitems#154]
**Describe the bug**
If you apply the ENTITY_LINGERING_THROW sound to a consumable such as a nether star with item throw ability, you will get errors in console as well as the consumable not being used

**To Reproduce**
1. Create a consumable, I did it using a nether star as the item_material
2. Add the ENTITY_LINGERING_THROW sound to it
3. Add the ITEM THROW ability with the nether star being the item like I did.
4. Check console log for errors and notice that the nether star is not consumed

**Expected behavior**
The nether star to disappear everytime you throw it.

**Server info:**
 - Spigot Build & Version: 1.15.2
 - Plugin Version: 5.4.2
 - Potential plugins linked to the issue

**Additional context**
https://pastebin.com/M2QXdeDZ

**Comment by Indyuce** [comment]
Check out this wiki page https://github.com/mmopluginteam/mmoitems/wiki/Item-Stats-and-Options#custom-item-sounds, you are not using the right sound names. You should be using the vanilla names here, not the "javadocs" names
