### ISSUE TITLE
Options involving enabling/disabling/editing the stackability of MMOItems

### ISSUE THREAD

**Issue by jacobmepstein** [mmopluginteam/mmoitems#157]
**Is your feature request related to a problem? Please describe.**
See this dupe glitch present when using items in MMOInventory: 
https://cdn.discordapp.com/attachments/710478507452661810/732801832337801256/dupeglitch.gif

It's assumed that this bug would be fixed if the items placed in MMOInventory were marked as unstackable. 

**Describe the solution you'd like**
The option to set a max-stack-size or just a boolean stackable/unstackable option.

**Describe alternatives you've considered**
Using UUIDs/NBTs to make items unstackable.

**Additional context**
This would be a nice QoL feature to have, as well as fixing this bug. Most items going into MMOInventories (rings, amulets) would make more sense if they were unstackable.

**Comment by Ehhthan** [comment]
This is added in the latest dev build.
