### ISSUE TITLE
MMOItemMana went wrong when players' game crashed

### ISSUE THREAD

**Issue by TUCAOEVER** [mmopluginteam/mmoitems#158]
**Describe the bug**
When player quit the game, console will get nullpointerexception error

**To Reproduce**
Whenever player join and quit the game

**Screenshots**
![image](https://user-images.githubusercontent.com/43756134/87855424-d534ed80-c94a-11ea-8f41-918d4bda577f.png)

**Server info:**
 - 1.15.2 Paper
 - MMOItems 5.5.3
 - MMOItems MMOItemMana

**Additional context**

**Comment by Joshinn-mc** [comment]
Not enough information. Please provide a full log.

**Comment by TUCAOEVER** [comment]
[2020-07-17-3.log](https://github.com/mmopluginteam/mmoitems/files/4945392/2020-07-17-3.log)

**Comment by Indyuce** [comment]
Will be fixed in the next build of MMOItems/MMOLib/MMOItemsMana
