### ISSUE TITLE
Add Vanilla drops to CustomBlocks drop Table

### ISSUE THREAD

**Issue by iPymad** [mmopluginteam/mmoitems#160]
Hi, just want to suggest to add Vanilla drops to CustomBlocks drop Table.

**Comment by Indyuce** [comment]
MMOItems is not really a drop management plugin. If you happen to be using MMOCore, it has a complex drop table solution for MI custom blocks and vanilla blocks as well.

**Comment by iPymad** [comment]
Ok, thanks, i'll use MMOCore then
