### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by DarkPaJl** [mmopluginteam/mmoitems#164]
Good day when I try to move the item that should enchant the sword to +1, I get an error in the console, although the charms through the workbench work and through the supplies give an error

![image](https://user-images.githubusercontent.com/68385624/88201474-134b4d80-cc7a-11ea-9f98-16857b261dbf.png)

**Comment by DarkPaJl** [comment]
Help me!

**Comment by ASangarin** [comment]
I'll have a look at it.

**Comment by ASangarin** [comment]
Fixed in latest.
