### ISSUE TITLE
BossShopPro+ LimitedUses conflict 

### ISSUE THREAD

**Issue by ZwingGX** [mmopluginteam/mmoitems#166]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**

https://pastebin.com/YGJvv2qn

**Describe the bug**

The mmoitem does not work when using LimitedUses. (BossShopPro Addon)

LimitedUses : https://www.spigotmc.org/resources/limiteduses-bsp-allows-to-limit-the-amount-of-uses-of-shop-items.26275/

BossShopPro: https://www.spigotmc.org/resources/bossshoppro-the-most-powerful-chest-gui-shop-menu-plugin.222/

**Server info:**
 - Paper 1.16 (paperclip-101)
 - MMOItems 5.5.4
 - MMOLib 1.2.5
 - BossShopPro 2.09
 - LimitedUses 1.1.0

**Comment by ASangarin** [comment]
Pretty sure this isn't an issue on our end.

**Comment by Indyuce** [comment]
Give the solution to #142 a try

**Comment by HoneyBearc** [comment]
Give the solution to #142 a try. Check the latest version of the development version has been added, but still have this problem

**Comment by ZwingGX** [comment]
I solved it by referring to #142. Thank you.
