### ISSUE TITLE
Show stat upgrades instead of adding them

### ISSUE THREAD

**Issue by Ithirul** [mmopluginteam/mmoitems#170]
**Is your feature request related to a problem? Please describe.**

When upgrading items, the only thing you can add is a change to the name of the item (for example Sword → Sword +1).However, every stat that was boosted by the upgrade gets directly added to the stats, not showing for how much the stat was boosted.

**Describe the solution you'd like**

Let's say I have a sword, and for every upgrade, its damage goes up by 15.

Instead of having:
    Damage: 5 → Upgrade → **Damage: 20**
The lore could show:
    Damage: 5 → Upgrade → **Damage: 5 (+15)**

This way, one can know exactly how much the upgrade has improved their item.

The way I can think of adding this would be in the config.yml, in the upgrade section:

item-upgrading:
    name-suffix: '+#lvl#'
    display-in-name: true
    **attack-damage-lore-show: false**

or:

    **lore-show:false**

Which could act as a "global" option.

With false keeping it the original way, and true adding the extra lore next to the stat. This way it won't break the lore of items that people have already made, and gives the option for each person to add this new option or leave it how it was.

**Describe alternatives you've considered**

The other way I can think of adding this would be in the lore-format.yml:

Instead of:
 '#attack-damage#'
We could be able to add:
 '#attack-damage# #attack-damage-upgrade#''

But I'm not sure if it's even possible to add 2 stats in one line without breaking everything.

The last alternative I can think of is having an optional piece of text like in the first solution, but adding it in the upgrade-template instead of the config.yml:

weapon-default:
    attack-damage: 3%
    **attack-damage-lore-show: false** // **lore-show: false**

Same as before, by keeping false as the default, it gives the option of leaving everything how it was, and letting each person change the stat that they want.

**Comment by Indyuce** [comment]
Nice idea although we will probably have to wait for MMOItems 6 to implement that

**Comment by Ehhthan** [comment]
Newest dev build attempts to add this.
