### ISSUE TITLE
Use money as condition at crafting stations

### ISSUE THREAD

**Issue by jacobmepstein** [mmopluginteam/mmoitems#173]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Similar to these conditions, https://github.com/mmopluginteam/mmoitems/wiki/Recipe-Conditions, one that links into Vault balance:

`money{amount=<amount>}`

**Describe alternatives you've considered**
It might be possible thru Denizen scripting to run a `money take` command on crafting trigger, but it's not ideal. This is much easier.

**Additional context**
None

**Comment by blek-id** [comment]
Pending indy's mmolib currency API

**Comment by Ehhthan** [comment]
Added in latest dev builds.
