### ISSUE TITLE
[Bug] Upgrade-Station material bypass

### ISSUE THREAD

**Issue by Ghmmy** [mmopluginteam/mmoitems#174]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
-

**Describe the bug**
If a player wants to upgrade their item using the upgrade-station and fails, they can upgrade it for a 2nd time. No matter if they own the items or not. You also dont have to spamclick it, waiting a few seconds also works
https://imgur.com/a/ZV4YLbW
(skip to the end to see the bug)

This bug only appears when an upgrade fails.

**To Reproduce**
1. Get yourself the gear to upgrade, as well as the exact materials requires
2. Open the craft/upgade-station
3. Upgrade the item
4.1. If it fails, click a 2nd time on it. Delay between the clicks doesnt matter: you can even wait a few days, click it and the bug will appear
5.1. the item will try to upgrade again, even tho it shouldnt be possible since you no longer have the materials for it

4.2. if the upgrade succeeded, click a 2nd time on it
5.2. the item wont be upgraded and it will tell you you dont have the materials for it

**Expected behavior**
The expected behaviour, just like step 5.2, is that the game will tell you you dont have the required materials to upgrade it. 

**Screenshots**
-

**Server info:**
 - Spigot 1.15.2
 - MMOitems 5.4.2

**Additional context**
-

**Comment by blek-id** [comment]
Confirmed

**Comment by blek-id** [comment]
It should be fixed on the latest build.
