### ISSUE TITLE
BUG: Unidentified items when given

### ISSUE THREAD

**Issue by AyresAyres** [mmopluginteam/mmoitems#175]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
Link goes here

**Describe the bug**
No Console Log, When Item is given via any command, 1/10 times gives a unidentified item, that can't be identified

**To Reproduce**
1. mi giveall taco 32 32
2. Might work first few times, then
3. x1 unidentified item appears instead of the selected item
4. See console log...

**Expected behavior**
I expected /mi giveall taco
to give tacos.

**Screenshots**
https://ibb.co/Wz2PQsj
**Server info:**
 - 1.15.2
 - 5.5.3
 - None- From /mi commands

**Additional context**

**Comment by Grumblin** [comment]
solved - running cracked plugins
