### ISSUE TITLE
Crafting station inheritance

### ISSUE THREAD

**Issue by shockelite** [mmopluginteam/mmoitems#176]
Add crafting station inheritance to simply config for multi-tiered crafting stations.

For example:
Basic crafting station
Advanced crafting station (Inherits tier 1 recipes, and has its own recipes) 
Adamantium platinum super macro holy mega crafting station (Inherits tier 1 and 2 recipes, and has its own recipes) .. ect

**Comment by Indyuce** [comment]
Will be available in the next dev build. You'll need to add `parent: <station-id>` to your crafting station config
