### ISSUE TITLE
Requesting Public Javadocs

### ISSUE THREAD

**Issue by ArcticRaven** [mmopluginteam/mmoitems#178]
**Is your feature request related to a problem? Please describe.**

We would like to better integrate MMOItems into our custom combat system, but with limited API, we cannot do this quite yet

**Describe the solution you'd like**
A form of public javadocs for developers to use be available somewhere. 

**Describe alternatives you've considered**
Requesting and entire re-write and/or expansion of the API wiki sections. 

**Additional context**
I am currently using a custom coded combat system with MM dependency - though we would like to migrate our tools/weapons/equipment to MMOItems for extended functionality.

**Comment by Joshinn-mc** [comment]
As always, we would love to expand on our API and make it more readable, we will add updating the API and giving it more explanation to our tasks list, thank you for the suggestion!
