### ISSUE TITLE
Crafting Stations support for "amount: 0"

### ISSUE THREAD

**Issue by Maitlans** [mmopluginteam/mmoitems#179]
**Is your feature request related to a problem? Please describe.**
I'm not sure if being able to enter amount as 0 and it still outputting an item is a bug or not.

**Describe the solution you'd like**
When making the amount 0 no item is outputted.

**Additional context**
With the recent addition of commands to be executed when a recipe is created this expands the possibility to support other plugins, it would be good if we were able to make our selected output item be 0 so it may seem more natural if you execute a command to give the user an item from another plugin. Thank you.

**Comment by Ehhthan** [comment]
This is added in the latest dev build. [This is an example recipe](https://i.imgur.com/UCOxJhr.png) which shows the new option under the options tab, it is named output-item. You still need to have an item defined in the output so something is displayed. This item will not be given with output-item: false .

**Comment by Maitlans** [comment]
> This is added in the latest dev build. [This is an example recipe](https://i.imgur.com/UCOxJhr.png) which shows the new option under the options tab, it is named output-item. You still need to have an item defined in the output so something is displayed. This item will not be given with output-item: false .

Hey I tested the new feature and I think it has a dupe bug, whenever I craft and get the items in the queue it'll execute the commands  and no output but I'll receive all of the ingredients back into my inventory being able to craft infinitely.
https://i.gyazo.com/8a3c3f4e6d9679e7585459c9ee5aed69.mp4

**Comment by Maitlans** [comment]
Another bug I found, when crafting on stations that don't have "output-item: false" will output with an error not giving the item.
https://pastebin.com/CwA8pPbh

**Comment by Ehhthan** [comment]
I can't replicate, the second issue but I can replicate the dupe. Can you send your crafting station recipe that produces the null error?

**Comment by Ehhthan** [comment]
Releasing a new build that should both issues.

**Comment by Maitlans** [comment]
Tested both issues and they appear fixed, awesome work! I don't know if closing is the right thing or something, but I'll leave it up to you. Thank you!
