### ISSUE TITLE
[REQUEST]Which MMOITEMS version can be use for 1.12.2 spigot?

### ISSUE THREAD

**Issue by MERRYACS** [mmopluginteam/mmoitems#181]
Hello guys i knew this is a dumb question, but for some reason i can't update server version to higher. So I am here to ask which version can be use for 1.12.2 spigot?

**Comment by jacobmepstein** [comment]
You can try some older legacy versions, but we do not provide support for version prior to 1.13. We recommend updating to 1.15 or higher.
