### ISSUE TITLE
Console spammed with task errors non-stop.

### ISSUE THREAD

**Issue by Crysillion** [mmopluginteam/mmoitems#182]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
[Fri, 31. Jul 2020 09:30:40 CDT ERROR] Could not pass event PlayerInteractEvent to MMOItems v5.5.3-SNAPSHOT
[Fri, 31. Jul 2020 09:30:40 CDT WARN] Task #2009 for MMOItems v5.5.3-SNAPSHOT generated an exception
[Fri, 31. Jul 2020 09:30:40 CDT ERROR] Could not pass event EntityDamageByEntityEvent to MMOItems v5.5.3-SNAPSHOT
[Fri, 31. Jul 2020 09:30:40 CDT ERROR] Could not pass event PlayerInteractEvent to MMOItems v5.5.3-SNAPSHOT
[Fri, 31. Jul 2020 09:30:41 CDT WARN] Task #2008 for MMOItems v5.5.3-SNAPSHOT generated an exception

**Describe the bug**
Not sure what happens. If I load up the server with a fresh MMOItems install, it just spams with these errors non-stop. What gives?

**To Reproduce**
Happens when I just load the server with the plugin.

**Server info:**
 - Paper #129
 - MMOItems 5.5.3

**Comment by AshenGaming** [comment]
Please update to the latest dev builds for MMOItems and MMOLib.

MMOItems 5.5.4 - https://www.mythicmobs.net/index.php?pages/dev-mmoitems/
MMOLib 1.2.6 - https://github.com/mmopluginteam/mmolib/releases/

**Comment by Joshinn-mc** [comment]
Same thing that ashen said, 1) you didn't provide a full log to see any actual cause of the error and 2) updating your plugins to latest versions will fix this 99/100 times.

MMOItems 5.5.4 - https://www.mythicmobs.net/index.php?pages/dev-mmoitems/
MMOLib 1.2.6 - https://github.com/mmopluginteam/mmolib/releases/
