### ISSUE TITLE
Movement Speed bugged in 1.16.1

### ISSUE THREAD

**Issue by MidnightSugar** [mmopluginteam/mmoitems#183]
**Describe the bug**
Movement speed will given to the player when they hold/wear the item normally, but when they stop holding/wearing the item, they still have the movement speed effect. Also, the movement speed itself feels like it is 100x faster than it should be.

**To Reproduce**
1. Add movement speed of 0.02 to item.
2. Notice how fast you will run.
3. Stop holding the item.
4. You will still have the speed boost until you relog.

**Expected behavior**
Movement speed is not the same as it was 1.15, and it should disable when not using the item.

**Server info:**
 - Paper 130, Minecraft 1.16.1
 - MMOItems 5.5.3, MMOLib 1.2.4.

**Comment by jacobmepstein** [comment]
Please update to the latest dev builds for MMOItems and MMOLib. This issue should be fixed.

MMOItems 5.5.4 - https://www.mythicmobs.net/index.php?pages/dev-mmoitems/
MMOLib 1.2.6 - https://github.com/mmopluginteam/mmolib/releases/

**Comment by Joshinn-mc** [comment]
Like jacob said up there, this issue is not present for me on latest versions of the plugin on 1.16.1.

MMOItems 5.5.4 - https://www.mythicmobs.net/index.php?pages/dev-mmoitems/
MMOLib 1.2.6 - https://github.com/mmopluginteam/mmolib/releases/
