### ISSUE TITLE
Misspelling for creating item

### ISSUE THREAD

**Issue by Elspar2** [mmopluginteam/mmoitems#184]
**Describe the bug**
When creating an item, the tooltip that appears when hovering over 'Required Class' says "The class you need to profress to use your item." Profess is spelled incorrectly.
![image](https://user-images.githubusercontent.com/32557628/89078573-43fe4780-d34a-11ea-82ab-5a445b08451a.png)

**Comment by Ehhthan** [comment]
Will be fixed in newest dev builds.
