### ISSUE TITLE
Full Set of MMOCore Triggers at Crafting Stations

### ISSUE THREAD

**Issue by jacobmepstein** [mmopluginteam/mmoitems#186]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great to have the [full set of MMOCore triggers](https://github.com/mmopluginteam/mmocore/wiki/Quest-Folder#available-trigger-types) available to use at MMOItems Crafting Stations. This would greatly improve compatibility

**Describe alternatives you've considered**
With the addition of running commands as triggers in a recent dev build, it has greatly increased the abilities and customization of crafting stations. It's probably doable to do all of the triggers with commands, but it's a hacky way and built-in triggers would be much easier.

**Additional context**
None.

**Comment by Ehhthan** [comment]
The only ones that I think should be added are mmoitem, item, and mmskill. The others should be done through conditions, which money will be added to soon.

**Comment by Ehhthan** [comment]
Added to latest dev build.
