### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by MusicTW** [mmopluginteam/mmoitems#195]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
https://pastebin.com/Nb04hKkQ

**Describe the bug**
error at the server

**Expected behavior**
All commands are error

**Server info:**
Version: git-Paper-128(MC:1.16.1)
MMOItems: v5.5.4-3376
MMOLib:1.2.6   MMOCore:v1.4.2-SNAPSHOT-218

**Comment by jacobmepstein** [comment]
This error is not enough. Attach a full server startup log.

**Comment by MusicTW** [comment]
https://pastebin.com/UuZffity

**Comment by Ehhthan** [comment]
You will need to update to the latest PlaceholderAPI

**Comment by MusicTW** [comment]
ok  thx
