### ISSUE TITLE
Arrow Velocity doesn't make sense.

### ISSUE THREAD

**Issue by Crysillion** [mmopluginteam/mmoitems#202]
Going to keep this short because it's pretty straight-forward.

When modifying Arrow Velocity, for example to 1.2, it puts 1.2% into the lore, which doesn't make much sense.

https://cdn.discordapp.com/attachments/345320261584814082/741303218084118648/unknown.png

Surely it's 1.2x or 120%?

**Comment by Indyuce** [comment]
It's 1.2x, you will need to remove the % from your language files
