### ISSUE TITLE
Release an API jar to develop against

### ISSUE THREAD

**Issue by rxdn** [mmopluginteam/mmoitems#203]
**Is your feature request related to a problem? Please describe.**
One of my users has requested that I add MMOItems support to my plugin. I'd like to add support, however, I don't particularly want to shell out 18 euros on it to add support for 1 user and then never use it again.

**Describe the solution you'd like**
It'd be ideal if there was a jar available with only the API method signatures included that developers could download for free.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jacobmepstein** [comment]
We have had this requested before and plan on releasing an API version alongside better API documentation, however for the time being we’ve always told people that we have no problem if they share their jar with a developer to add support for things. Ask your user!
