### ISSUE TITLE
API - How to detect if the ItemStack is a MMOItem

### ISSUE THREAD

**Issue by apatuka** [mmopluginteam/mmoitems#204]
Hi, i can't find any documentation about how can i detect if an ItemStack is a MMOItem.

Do you have any example ?

Thanks !

**Comment by SaltyAimbOtter** [comment]
That the first thing on the API page xD
https://github.com/mmopluginteam/mmoitems/wiki/Main-API-Features#checking-if-an-itemstack-is-from-mi

**Comment by jacobmepstein** [comment]
See above comment. Thanks @SaltyAimbOtter!
