### ISSUE TITLE
Custom Blocks Pack Incorrectly Displays Block 053

### ISSUE THREAD

**Issue by Elspar2** [mmopluginteam/mmoitems#206]
--latest.log:
https://pastebin.com/Fz8AzL66

--Bug:
Downloaded the default resource pack for custom blocks from the link using "/mi browse" in-game, when a block is designated as 053 it uses the 053 texture when held, but uses the 021 texture when placed.

--To Reproduce:
1.Download resource pack from in-game.
2.Activate resource pack.
3.Set a custom block ID to 53.
4.Reload mmoitems in-game.
5.Get custom block, handheld texture is correctly displayed as 053.
6.Place custom block, placed texture is INCORRECTLY displayed as 021.

--Expected Behavior:
Place custom block, placed texture is correctly displayed as 053.

**Screenshots**
https://cdn.discordapp.com/attachments/619382883341172757/741862351560769688/unknown.png
https://cdn.discordapp.com/attachments/619382883341172757/741862446758887474/unknown.png
https://cdn.discordapp.com/attachments/619382883341172757/741862577885413426/unknown.png

**Server info:**
    - Spigot 1.15.2
    - MMOItems-5.5.4

**Comment by Ehhthan** [comment]
Will be fixed in new custom block overhaul.
