### ISSUE TITLE
damage boost bug

### ISSUE THREAD

**Issue by Zacushka** [mmopluginteam/mmoitems#73]
**Describe the bug**

MMOitems is not effecting the damage output of custom mythic mob skills.
Here is a demonstration:
https://youtu.be/hc0816okOis

**To Reproduce**

1. add any damage increaser to an item with a custom mythic mobs skill that does damage.

2. Attack entity...

3. see no change in results.

**Expected behavior**

increase or decrease in damage output with custom mythic mob skills.

**Screenshots**

see video link

**Server info:**
 - Spigot Build & Version
spigot 1.14.4
mm 4.9 
mmoitems 5.3.2 build 125

**Additional context**

**Comment by Zacushka** [comment]
build 148 still has the issue.

**Comment by Zacushka** [comment]
update.  Using the mmoitems damage placeholder is the issue.  Using an integer works just fine.

**Comment by Indyuce** [comment]
This is most likely a MythicMobs issue, all MMOItems does is register the damage placeholder and make it return a certain value. If using an integer works, that means MM skills does trigger MI formulas with integers but not with placeholders however from MI perspective it most likely does not change anything.

**Comment by Zacushka** [comment]
Anything like if I bring this to the attention of missing mobs just going to push it to the wayside as something that is not their problem. You guys seem pretty close do you mind bringing up a compatibility request on my behalf as I feel like you know the problem better than I do .

**Comment by Indyuce** [comment]
I will ask MythicMobs devs

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
